In [1]:
import numpy as np

In [3]:
#reshape elements in numpy
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#reshape using linspace
b=np.linspace(2,8,10).reshape(2,5)
print(b)

[[2.         2.66666667 3.33333333 4.         4.66666667]
 [5.33333333 6.         6.66666667 7.33333333 8.        ]]


In [14]:
n=np.array([23,4,56,7,89,10,12,3]).reshape(2,2,2)
print(n)

[[[23  4]
  [56  7]]

 [[89 10]
  [12  3]]]
