In [17]:
#variable
a=10
print("I am", a, "years old");

I am 10 years old


In [6]:
#arthimetic operations of 2 int numbers

a=int(input("Enter a value"));
b=int(input("Enter b value"));
c=a+b;
print("Sum is c",c);
print("Sub is",a-b)
print("Mul is",a*b)
print("quotient is",a/b)
print("remainder is",a%b)
print("power of a to be is",a**b)
print("Floor division is",a//b)

Enter a value2345
Enter b value23
Sum is c 2368
Sub is 2322
Mul is 53935
quotient is 101.95652173913044
remainder is 22
power of a to be is 326050959193591141104763422182437632534688094415238583843780863285064697265625
Floor division is 101


In [1]:
#take a number from the user which is a salary.If the salary is more than 50000,there is a 10% tax deduction.Print his final salary.
s=int(input("Enter the salary"))
if(s>=50000):
  s=s-(s*(10/100))
  print("Salary is",s)
else:
  print("Salary is less than 50000")

Enter the salary70000
Salary is 63000.0


In [13]:
#get the salary from the user.If the salary is more than or equal to 50k.apply the 10% tax deduction.if the salary is less than 50k,apply 5% tax.If the salary is more than 70k,apply 12% tax.If the salary exceeds 1lakh print you are promoted to nxt level.
s=int(input("Enter the salary"))
if(s<=50000):
  s=s-(s*(5/100))
  print("Salary is",s)
elif(s>=50000 and s<70000):
  s=s-(s*(10/100))
  print("Salary is",s)
elif(s>=70000 and s<100000):
  s=s-(s*(12/100))
  print("Salary is",s)
else:
  print("You are promoted")

Enter the salary50000
Salary is 47500.0


In [14]:
ran=range(1,11)
print(ran)

range(1, 11)


In [15]:
#for loop
a=int(input("Enter the value"))
range=range(1,11)
for i in range:
  print(a,"X",i,"=",a*i)

Enter the value78
78 X 1 = 78
78 X 2 = 156
78 X 3 = 234
78 X 4 = 312
78 X 5 = 390
78 X 6 = 468
78 X 7 = 546
78 X 8 = 624
78 X 9 = 702
78 X 10 = 780


In [16]:
#while
a=int(input("Enter the number:"))
i=1
while(i<11):
  print(a,"X",i,"=",a*i)
  i=i+1


Enter the number:41
41 X 1 = 41
41 X 2 = 82
41 X 3 = 123
41 X 4 = 164
41 X 5 = 205
41 X 6 = 246
41 X 7 = 287
41 X 8 = 328
41 X 9 = 369
41 X 10 = 410


In [19]:
#create a list
l1=[1,30,'prani']
print(l1[1:2])


[30]


In [20]:
#create heterogeneous list
l=[1,'chat',True,83,20.2]
for i in l:
  print(i)

1
chat
True
83
20.2


In [22]:
#mutable:
l.append("appended")#adds element at back of the list
print(l)
l.insert(4,"Oyii") #listname.insert(index,element)
print(l)

[1, 'chat', True, 83, 20.2, 'appended', 'appended']
[1, 'chat', True, 83, 'Oyii', 20.2, 'appended', 'appended']


In [23]:
#append or extend      #list1.extend(list2)
l2=["insta",6,"krishna",12] #or l.extend(l2) -> l=l+l2
print(l+l2)

[1, 'chat', True, 83, 'Oyii', 20.2, 'appended', 'appended', 'insta', 6, 'krishna', 12]


In [28]:
#deleting
l2.remove(12)  #listname.remove(element)
print(l2)

['insta', 'krishna']


In [29]:
#pop
l3=[34,'amma',43.5]
l3.pop(2)  #listname.pop(index)
print(l3)

[34, 'amma']


In [30]:
#clear
l1.clear()
print(l1)

[]


In [31]:
#create a list of random  10 integers elements.print their squares.save these squares in a new list.
s=[2,34,57,90,12,37,89,10,65,18]
p=[]
for i in s:
  p.append(i**2)
print(p)

[4, 1156, 3249, 8100, 144, 1369, 7921, 100, 4225, 324]


In [32]:
#list comprehension
#new list=[output for]
s=[23,12,64,87,32]
p=[i*i for i in s]
print(p)

[529, 144, 4096, 7569, 1024]


In [33]:
p=[i*i for i in s if i>50]
print(p)

[4096, 7569]


In [1]:
#list comprehension
#if-else
#new list=[(st of if) if(cond) else (st of else) for]
l=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in l]
print(res)

['X', 4489, 'X', 'X', 4761]


In [2]:
#take salary from the user.If the salary is less than 50k,10% tax.otherwise 15% tax
s=int(input("Enter the salary"))
l=[s-(s*0.1) if s>50000 else s-(s*15/100)]
print(l)

Enter the salary600000
[540000.0]


In [9]:
l1=[800000,30000,20000,70000,23000]
l=[i-i*0.1 if s<=50000 else i-i*0.15 for i in l1]
print(l)

[680000.0, 25500.0, 17000.0, 59500.0, 19550.0]


In [11]:
#dictionary
dict1={"Mentor":'Jwalitha',6:'prani',12:'Sai',34:'amma',64:'nanna'}
print(dict1)
print(dict1.keys())
print(dict1.values())

{'Mentor': 'Jwalitha', 6: 'prani', 12: 'Sai', 34: 'amma', 64: 'nanna'}
dict_keys(['Mentor', 6, 12, 34, 64])
dict_values(['Jwalitha', 'prani', 'Sai', 'amma', 'nanna'])


In [15]:
dict1={"Mentor":'Jwalitha',6:'prani',12:'Sai',34:'amma',64:'nanna'}
print(dict1[34])

amma


In [19]:
dict3={"dept":"CSE","Details":{"Year":"II","Sec":"D","Count":71}}
print(dict3["Details"]["Sec"])
print(dict3["Details"]["Year"])
print(dict3["Details"]["Count"])

D
II
71


In [20]:
idl=[34,56,78,50]
names=["Joe","Suchi","Prani","Sai"]
new_zip=(zip(idl,names))
for i in new_zip:
  print(i)

(34, 'Joe')
(56, 'Suchi')
(78, 'Prani')
(50, 'Sai')


In [21]:
idl=[34,56,78,50]
names=["Joe","Suchi","Prani","Sai"]
print(dict(zip(idl,names)))


{34: 'Joe', 56: 'Suchi', 78: 'Prani', 50: 'Sai'}


In [23]:
#NUMPY
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [27]:
#2d array
import numpy as np
A=np.array([[1,2,3,4],[6,7,8,9]]) #2d array
#elements in each row=columns
print(A.ndim)
print(A.shape)
print(A)

2
(2, 4)
[[1 2 3 4]
 [6 7 8 9]]


In [29]:
#3d array
import numpy as np
A=np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]]) #3d array
#elements in each row=columns
print(A.ndim)
print(A.shape)
print(A)

3
(1, 3, 4)
[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]


In [30]:
import numpy as np
A=np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[4,5,6,7]]]) #3d array
#elements in each row=columns
print(A.ndim)
print(A.shape)
print(A)

3
(2, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [4 5 6 7]]]


In [31]:
A=np.ones((2,3)) # groups,rows,columns
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
A=np.zeros((2,4,3))
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [35]:
#identity matrix
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
A=np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [42]:
#print all the numbers that are divisible by 8 using arange function b/w 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [45]:
#Splitting a range into n numbers with common differences
A=np.linspace(48,59,5)
print(A)  #dividing 12 parts b/w 2 and 3

[48.   50.75 53.5  56.25 59.  ]


In [ ]:
#tuple,sets,documentation,qr code